language: node_js
node_js:
  - "6"
  - "6.1"
install:
  - npm install
deploy:
  app: shop-client-api
  provider: heroku
  api_key:
    secure: xhl6+MmbYcH+HQfPq2KvDNSB9EJPh1RZHNIUUc17N9/TDk6JhXfc4dWH1STRmVKx4b98/18nstKwn6+yr0uJ3koEAzKwzIoyxzYLa6JC/7WyjYAyphvkbU0zZ3+9EA0K/DwtQFEm1Ylko3hbt5E97cA8ZwDYvMJLNwy4Sd10b9LPQ7ZP///RpErBMCi3HnXWbdF1qmMCFciMu19L1T3hPcTEr83rLT0zX5bz2xb7HnrFItBqXWTrM54GbzRVeHX4lA0bpMvAvHcwSiro2+R4RKliWNeiFPio5jVgt+5Y1swbBmmzrlZOG82V1JF/Kp4jwx5tmzYPnPF6Hu6TuqGKUvnl3SMDlWKZ7cFMfdlIc5Ecf59KnU9NIAdFTHZwIclNOkz+pFahyT16HPymsPMGj1gl1SpuBGUrwIsgWXq557sJhjkB+E1xiawSR/o+rHrWf84CyLeiPKwWPmjuR4whC8Hrr4rzFONmMXqXASYIB7wINXN/gNPf2a3023bJLAMAyOzJ/Vlx2aXdsfOnN2G9lENgwA9nQmcrtIyj1UBBw/QaYy40AJH1L2bYorrVHgihVLS3HgMjL+Vx1+uBVG7aOQ/Y7a6xJIfW5v5Sxfv4zS3dUD11UgeP3GrMZLVs/gF/G8DCKy+A6g3Wjo237XouACNWB3RH6ChZDCZN0uY46po=
